version: 2

jobs:
  node8:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npm test

  node10:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run: npm test

  node12:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build_and_test:
    jobs:
      - node8:
          filters:
            branches:
              ignore:
                - /^gh-pages$/
      - node10:
          filters:
            branches:
              ignore:
                - /^gh-pages$/
      - node12:
          filters:
            branches:
              ignore:
                - /^gh-pages$/

notify:
  webhooks:
    - url: https://bot.suddi.io/hooks/circle
