version: 2

jobs:
  docs:
    docker:
      - image: circleci/node:12
    steps:
      - run: status_code=$(curl --output /dev/null --head --silent --write-out '%{http_code}' https://suddi.github.io/node-object-to-object-mapper/)
      - run: if [[ $status_code != "200" ]]; then exit 1; fi

workflows:
  version: 2
  test:
    jobs:
      - docs

notify:
  webhooks:
    - url: https://bot.suddi.io/hooks/circle
